# Ejercicios de notebooks 7 y 8: Numpy y álgebra lineal

**Curso:** Ciencia de Datos en Python

**Catedrático:** Ing. Luis Leal

**Estudiante:** Dany Rafael Díaz Lux (21000864)

**Instrucciones:** Resolver ejercicios indicados en los notebooks 7 y 8: Numpy y álgebra lineal.

**Fecha de entrega:** 14 de abril de 2021

## Ejercicio 1
Investigar y ejemplificar diferencias entre np.array y np.matrix

### Diferencias entre numpy.array y numpy.matrix:
Numpy contiene la clase **array** y **matrix**; la clase **array** es de propósito general para la creación y computación numérica de arreglos de N dimensiones, mientras que **matrix** tiene la finalidad de facilitar computación de álgebra lineal para arreglos de 2 dimensiones.

Algunas diferencias específicas son:

### a. Operador *:
Para los arreglos creados con *numpy.array*, el operador de multiplicación elemento a elemento es asterisco ( * ); mientras que para arreglos creados con *numpy.matrix* actúa como multiplicación de matricial. Ejemplo:

In [31]:
# Importar numpy
import numpy as np

In [32]:
# Arreglos creados con numpy.array
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

# Arreglos creados con numpy.matrix
mat1 = np.matrix([[1,2], [3,4]])
mat2 = np.matrix([[5,6], [7,8]])

# Mostrar diferencias entre operadores
print('resultado arr1 * arr2 (element wise en np.array)')
print(arr1*arr2)
print('resultado mat1 * mat2 (multiplicación matricial en np.matrix)')
print(mat1 * mat2)

resultado arr1 * arr2 (element wise en np.array)
[[ 5 12]
 [21 32]]
resultado mat1 * mat2 (multiplicación matricial en np.matrix)
[[19 22]
 [43 50]]


### b. Atributos especiales:
Para arreglos creados con *numpy.array* se cuenta con el atributo *.T* que devuelve el arreglo transpuesto, mientras que para los arreglos creados con *numpy.matrix* además de *.T* se cuenta con otros atributos extras: *.I* que devuelve la matriz inversa, *.A* que devuelve la matriz como un arreglo de tipo *numpy.array*. Ejemplo:

In [33]:
# Atributo de arr1
print('arr1:')
print(arr1)
print('arr1.T:')
print(arr1.T)

arr1:
[[1 2]
 [3 4]]
arr1.T:
[[1 3]
 [2 4]]


In [34]:
# Atributos de mat1
print('mat1:')
print(mat1)
print('mat1.T')
print(mat1.T)
print('mat1.I')
print(mat1.I)
print('type(mat1), type(mat1.A)')
print(type(mat1), ',', type(mat1.A))

mat1:
[[1 2]
 [3 4]]
mat1.T
[[1 3]
 [2 4]]
mat1.I
[[-2.   1. ]
 [ 1.5 -0.5]]
type(mat1), type(mat1.A)
<class 'numpy.matrix'> , <class 'numpy.ndarray'>


### c. Constructores:
Mientras que *numpy.array* toma listas para inicializar sus arreglos, *numpy.matrix* puede tomar además cadenas como inicializadores. Ejemplo:

In [35]:
# Creación de un arreglo solo con listas
arr3 = np.array([[1, 1], [2, 2]])

# Creación con una cadena de texto
mat3 = np.matrix('[1 1; 2 2]')

print('arr3')
print(arr3)
print('mat3')
print(mat3)

arr3
[[1 1]
 [2 2]]
mat3
[[1 1]
 [2 2]]


## Ejercicio 2

Implementar en una funcion neural_network(X) la red neuronal definida por la siguiente arquitectura:

<img src="http://i.imgur.com/UNlffE1.png">

Podemos validar si fue correctamente implementada si usamos como entrada el vector x=[1,1] . Debemos obtener el resultado mostrado en la imagen.

Luego evaluar la red neuronal sobre la matriz de datos X(de manera vectorizada):

In [36]:
def sigmoid(x): #convertir los valores de x al rango de 0 a 1
    return 1/(1+np.exp(-x))

In [37]:
def neural_network(x):
    HL = np.array([[0.712, 0.355, 0.268], [0.112, 0.855, 0.468]])
    OL = np.array([[0.116], [0.329], [0.708]])
    
    xHL = np.matmul(x,HL)
    xHL = sigmoid(xHL)
    
    xOL = np.matmul(xHL, OL)
    xOL = sigmoid(xOL)
    
    return xOL

In [38]:
X = np.array([
    [0.1,2],
    [0.3,0.45],
    [5,9],
    [12,6],
    [7,5],
    [0.3,0.8],
    [12,5],
    [100,200],
    [7,8],
    [300,1500]])

In [39]:
neural_network(X)

array([[0.70244573],
       [0.66259284],
       [0.75933678],
       [0.75973948],
       [0.75802295],
       [0.6739704 ],
       [0.75954693],
       [0.76005845],
       [0.75952743],
       [0.76005845]])